// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YUZCUbYsu5LPEfBkcm-1TVTPV9j_B0I',
    appId: '1:116165797791:web:acf8d0b12f0348cef1ffaa',
    messagingSenderId: '116165797791',
    projectId: 'triple-prime',
    authDomain: 'triple-prime.firebaseapp.com',
    storageBucket: 'triple-prime.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YUZCUbYsu5LPEfBkcm-1TVTPV9j_B0I',
    appId: '1:116165797791:android:acf8d0b12f0348cef1ffaa',
    messagingSenderId: '116165797791',
    projectId: 'triple-prime',
    storageBucket: 'triple-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmVGj71Qs4gLrt6Wtbo1awl3bE8md6YQ',
    appId: '1:116165797791:ios:42048f3d8c8bb7fff1ffaa',
    messagingSenderId: '116165797791',
    projectId: 'triple-prime',
    storageBucket: 'triple-prime.firebasestorage.app',
    iosBundleId: 'com.tripleprime.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmVGj71Qs4gLrt6Wtbo1awl3bE8md6YQ',
    appId: '1:116165797791:ios:42048f3d8c8bb7fff1ffaa',
    messagingSenderId: '116165797791',
    projectId: 'triple-prime',
    storageBucket: 'triple-prime.firebasestorage.app',
    iosBundleId: 'com.tripleprime.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5YUZCUbYsu5LPEfBkcm-1TVTPV9j_B0I',
    appId: '1:116165797791:web:acf8d0b12f0348cef1ffaa',
    messagingSenderId: '116165797791',
    projectId: 'triple-prime',
    authDomain: 'triple-prime.firebaseapp.com',
    storageBucket: 'triple-prime.firebasestorage.app',
  );
}
